### ISSUE TITLE
Clicking status bar opens broken "system log" window

### ISSUE THREAD

**Issue by rquarry** [osrmt/osrmt#54]
The bottom most bar of the main application window and the bottom left corner of artifact windows appear to function as the "status bar". 

When this GUI element is clicked, a blank window titled, "System Log" opens. I attempted to try and generate some system log events by adding artifacts, but the behavior is always the same.

![Screenshot from 2020-04-26 08-12-12](https://user-images.githubusercontent.com/54045716/80307239-bed92480-8795-11ea-8d1e-c9595870d21c.png)

**Comment by rquarry** [comment]
Well, if there's one thing this application has going for it, it's logging. In the file osrmt/system_details.log I found:

java.lang.NullPointerException
	at com.osframework.appclient.system.SystemLogForm.addListeners(Unknown Source)
	at com.osframework.appclient.system.SystemLogForm.initialize(Unknown Source)
	at com.osframework.appclient.ui.components.UICenterSouthDialog.<init>(Unknown Source)
	at com.osframework.appclient.system.SystemLogForm.<init>(Unknown Source)
	at com.osframework.appclient.ui.common.GUI$3.call(Unknown Source)
	at com.osframework.appclient.ui.listeners.DoubleClickListener.mouseClicked(Unknown Source)
	at java.awt.Component.processMouseEvent(Component.java:6542)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6304)
	at java.awt.Container.processEvent(Container.java:2239)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4544)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
	at java.awt.Container.dispatchEventImpl(Container.java:2283)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
	at java.awt.EventQueue$4.run(EventQueue.java:733)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
	at org.GNOME.Accessibility.AtkWrapper$6.dispatchEvent(AtkWrapper.java:705)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

Not sure if it's evident, but "SystemLogForm.java" contains the GUI elements related to the "System Log" window pictured in my orginal post.
