### ISSUE TITLE
Password errors

### ISSUE THREAD

**Issue by Yazeeddsl** [osrmt/osrmt#56]
When I use the RUN to log in the application, shows me the ( user is DEMO and password is 0ieFWiUyniu9zCCR819JWg==) But it's says invalid password. I change it in the osrmt access db but still the same problem. 
anther problem is if I want ti use the run3tier shows me this 
(javax.naming.CommunicationException: Could not obtain connection to any of these urls: 127.0.0.1:1099 and discovery failed with error: javax.naming.CommunicationException: Receive timed out [Root exception is java.net.SocketTimeoutException: Receive timed out] [Root exception is javax.naming.CommunicationException: Failed to connect to server 127.0.0.1:1099 [Root exception is javax.naming.ServiceUnavailableException: Failed to connect to server 127.0.0.1:1099 [Root exception is java.net.ConnectException: Connection refused: connect]]]
	at org.jnp.interfaces.NamingContext.checkRef(NamingContext.java:1399)
	at org.jnp.interfaces.NamingContext.lookup(NamingContext.java:579)
	at org.jnp.interfaces.NamingContext.lookup(NamingContext.java:572)
	at javax.naming.InitialContext.lookup(Unknown Source)
	at com.osframework.ejb.reference.security.SecurityUtil.lookupHome(Unknown Source)
	at com.osframework.ejb.reference.security.SecurityUtil.getHome(Unknown Source)
	at com.osframework.ejb.reference.security.SecurityUtil.getSecurity(Unknown Source)
	at com.osframework.appclient.services.SecurityServices.getSecurityRef(Unknown Source)
	at com.osframework.appclient.services.SecurityServices.getAppControls(Unknown Source)
	at com.osframework.appclient.services.SecurityServices.getAppControls(Unknown Source)
	at com.osrmt.appclient.system.LoginController.start(Unknown Source)
	at com.osrmt.appclient.reqmanager.RequirementManagerController.start(Unknown Source)
	at com.osrmt.appclient.reqmanager.RequirementManagerController.main(Unknown Source)) 

Could you please help. 
Thanks

**Comment by markhu520** [comment]
I have the same error with desktop version 1.8 of this tool.

**Comment by markhu520** [comment]
I can access the OSRMT tool now, and the password should be “demo”, you can learn this information from youtube https://www.youtube.com/watch?v=3Dl9FmmECeE&t=20s.

mark hu
