### ISSUE TITLE
OSRMT 1.8 Windows 10 doesn't start

### ISSUE THREAD

**Issue by H-CHETTOUR** [osrmt/osrmt#58]
when i execute the run.bat the app starts but freezes on the image of the earth ( the first frame).

**Comment by mtalha2621** [comment]
I am facing the exact same issue, any fixes for this yet?

**Comment by ZoranPandovski** [comment]
Hi @H-CHETTOUR, @rwnhtpl this project wasn't maintained for a long time. I will check with Alan what is the plan. As I remember there was slack community too in case you want to join or contribute to the project.

**Comment by rquarry** [comment]
I think this might be related to issue #53.

**Comment by rquarry** [comment]
@ZoranPandovski Do you have permissions on this repo to add collaborators? Can you add me as a collaborator? Yes, this project has been dormant for some time, but there still appears to be interest from others. I'd be happy to close out some issues and continue contributing. I'm the last person to submit code to this project.

**Comment by yuuyins** [comment]
edit: my issue is probably unrelated and i solved it https://github.com/osrmt/osrmt/issues/59#issuecomment-1121311928

both 1.8 and <s>master</s> develop won't start for me with error

```
com.osrmt.appclient.system.ConnectionXmlNotFoundException
	at com.osrmt.appclient.system.LoginController.start(Unknown Source)
	at com.osrmt.appclient.reqmanager.RequirementManagerController.start(Unknown Source)
	at com.osrmt.appclient.reqmanager.RequirementManagerController.main(Unknown Source)
```

https://github.com/osrmt/osrmt/blob/b4909cd81e53244c15fe4e1a9218a91e37f2965a/src/main/com/osrmt/appclient/system/LoginController.java#L61

https://github.com/NixOS/nixpkgs/pull/163400

**Comment by ZoranPandovski** [comment]
@rquarry You should have access now.

**Comment by BPloe** [comment]
I'm having this same problem. It gets stuck on the earth splash screen. I've left it for an hour and it never progressed past that.

**Comment by adamoutler** [comment]
same

**Comment by discoverycamel** [comment]
I think its related to the version of Java Runtime you have installed.
I had this issue with  the microsoft open JRE version 21. When I went back to 8, it worked. 
Running the run.sh using git bash was more helpful - you can see the exception being thrown in the code relating to (IIRC) a swing component.
So maybe try Java 1.8? That's working for me.

**Comment by adamoutler** [comment]
Java 8 is past life expectancy and in extended support phase. You should be using java 23 now.  Legacy versions of java shouldn't be used.
